# Generated by Django 3.1.3 on 2020-12-20 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('ID', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('lastEditTime', models.DateTimeField(auto_now_add=True)),
                ('itemName', models.CharField(max_length=20, verbose_name='餐品名')),
                ('itemText', models.TextField(verbose_name='餐品简介')),
                ('price', models.FloatField(verbose_name='餐品价格')),
                ('picture', models.ImageField(null=True, upload_to='img/', verbose_name='餐品图片')),
            ],
            options={
                'verbose_name': '餐品数据表',
                'db_table': 'Menu',
                'ordering': ['-lastEditTime'],
            },
        ),
        migrations.CreateModel(
            name='Usr',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='账号')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('location', models.CharField(max_length=50, verbose_name='地址')),
                ('phoneNumber', models.CharField(max_length=50, verbose_name='电话号码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('stage', models.CharField(choices=[('Customer', '顾客'), ('Merchant', '商家'), ('Dispatcher', '送餐员')], max_length=20, verbose_name='身份')),
                ('lastLoginTime', models.DateTimeField(auto_now_add=True, verbose_name='最后登录时间')),
            ],
            options={
                'verbose_name': '用户数据表',
                'db_table': 'Usr',
                'ordering': ['-lastLoginTime'],
            },
        ),
        migrations.CreateModel(
            name='WaitCash',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='单号')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='生成时间')),
                ('price', models.FloatField(verbose_name='金额')),
                ('note', models.TextField(verbose_name='备注')),
                ('是否转账', models.BooleanField(default=False)),
                ('usrID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.usr', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '待提现数据表',
                'db_table': 'WaitCash',
                'ordering': ['-ID'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('createTime', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='生成时间')),
                ('orderID', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='订单号')),
                ('stage', models.CharField(choices=[('待支付', '顾客已下单，未支付'), ('已支付', '顾客已下单，已支付'), ('制作中', '商家已接单'), ('配送中', '配送员已接餐'), ('已完成', '顾客已接餐'), ('已评价', '顾客已接餐')], max_length=20, verbose_name='订单状态')),
                ('commentMerchant', models.TextField(verbose_name='餐品评价')),
                ('commentDispatcher', models.TextField(verbose_name='配送评价')),
                ('CustomerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CustomerID', to='cmdb.usr', verbose_name='顾客ID')),
                ('DispatcherID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DispatcherID', to='cmdb.usr', verbose_name='送餐员ID')),
                ('MerchantID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MerchantID', to='cmdb.usr', verbose_name='商家ID')),
                ('itemID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.menu', verbose_name='餐品号')),
            ],
            options={
                'verbose_name': '订单数据表',
                'db_table': 'Order',
                'ordering': ['-orderID'],
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='merchantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.usr', verbose_name='商家账号'),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('createTime', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='生成时间')),
                ('billID', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='账单号')),
                ('price', models.FloatField(verbose_name='金额')),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.order', verbose_name='订单号')),
                ('usrID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.usr', verbose_name='用户账号')),
            ],
            options={
                'verbose_name': '账单数据表',
                'db_table': 'Bill',
                'ordering': ['-createTime'],
            },
        ),
    ]
