# Generated by Django 3.1.3 on 2020-12-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usr',
            name='active',
        ),
    ]
