# Generated by Django 3.1.2 on 2020-12-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20201214_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stage',
            field=models.CharField(choices=[('已下单', '顾客已下单'), ('制作中', '商家已接单'), ('配送中', '配送员已接餐'), ('已完成', '顾客已接餐')], max_length=20, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='usr',
            name='stage',
            field=models.CharField(choices=[('Customer', '顾客'), ('Merchant', '商家'), ('Dispacher', '送餐员')], max_length=20, verbose_name='身份'),
        ),
    ]
