# Generated by Django 3.1.3 on 2020-12-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20201217_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='picture',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='餐品图片'),
        ),
    ]
