# Generated by Django 2.1.5 on 2020-12-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0013_auto_20201219_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitcash',
            name='是否转账',
            field=models.BooleanField(default=False),
        ),
    ]
