# Generated by Django 2.1.5 on 2020-12-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0014_waitcash_是否转账'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='lastEditTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
