# Generated by Django 2.1.5 on 2020-12-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0015_auto_20201219_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='lastEditTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
